### ISSUE TITLE
W6 - Assurance Cases

### ISSUE THREAD

**Issue by Lord-Tiger** [Lord-Tiger/CYBR8420_Fall24#10]

**Comment by Lord-Tiger** [comment]
Yasir's assurance case:

![Assurance_Case1_Minimizes_Data_Disclosure](https://github.com/user-attachments/assets/f5e120ca-2e74-48c9-9009-445186d8098d)

**Comment by gilbeb** [comment]
![Image](https://github.com/user-attachments/assets/40788fb7-b9fb-4166-bc32-3264249a6a30)

**Comment by gilbeb** [comment]
![Image](https://github.com/user-attachments/assets/3af40b53-6fd5-4795-8e81-aa774bfcb1c9)

**Comment by asongne** [comment]
For this project, we held a meeting on Discord last Wednesday to brainstorm various assurance cases. During the session, each of us used AI tools to help identify potential approaches, and we generated about six different options. After reviewing them, we each selected one to develop further in preparation for our meeting with the professor on Thursday.

During the call with the professor, we received valuable feedback and began refining our project accordingly. Our first assurance case focuses on the confidentiality of patient data, the second ensures that users have access to the software based on their designated roles, and the third addresses preventing unauthorized access to billing and insurance information.

**Comment by gilbeb** [comment]
![Image](https://github.com/user-attachments/assets/f7a6d84c-36ed-4ccc-9f77-9f43b4b801e8)

**Comment by asongne** [comment]
[Assurance case updated.pdf](https://github.com/user-attachments/files/17370905/Assurance.case.updated.pdf)

**Comment by asongne** [comment]
[Assurance case updated1.pdf](https://github.com/user-attachments/files/17371061/Assurance.case.updated1.pdf)

**Comment by asongne** [comment]
![Assurance case (1)](https://github.com/user-attachments/assets/90f701e4-9796-4261-b99a-ef9f04160990)

**Comment by asongne** [comment]
Abdoul: For this project, I developed the top-level claim: "OpenEMR ensures that only authorized users can access the system and perform actions based on their roles." I also contributed to the team's reflection process, assisted in reviewing the other cases, and actively participated in brainstorming the assurance cases we needed to focus on for this task.
