### ISSUE TITLE
Project proposal

### ISSUE THREAD

**Issue by asongne** [Lord-Tiger/CYBR8420_Fall24#3]
Motivation:
For this project, we focused on the healthcare sector due to one of our team members' professional experience in the field, which we believed would bring valuable insights.
We selected OpenEMR as our subject, as it is a globally recognized open-source healthcare software, used by institutions such as the Peace Corps.
OpenEMR is fully functional, allowing patients to schedule appointments, manage payments, and access their prescriptions and lab results. 
Healthcare providers can use the platform to view appointments, order lab tests, prescribe medication, and receive clinical decision support. 
Additionally, we chose this project because it is a multi-user platform that faces various security threats and challenges, making it a compelling subject for our analysis.

Description:
According to the decription provided on OpenEMR's website, The community of behind the project is committed to maintaining OpenEMR as a free,
open-source software solution for medical practices, the platform enjoys robust support from both users and developers. 
With over 4,000 downloads per month and contributions from more than 174 developers and companies, 
OpenEMR is the most widely used free electronic medical records system today. Its codebase is continuously improved through open collaboration, 
and the software is available in more than 30 languages, making it a truly global solution for healthcare providers.

Team work:
After the team was formed, we initially faced challenges with communication. However, we resolved this by setting up a Discord server and creating a GitHub repository as required for the class. 
While one team member is still missing, we are moving forward with the project using the resources we have.
Throughout the process, we held two meetings, during which we divided the project tasks relatively equally, leveraging each team member’s strengths. 
We plan to hold one final meeting to consolidate our work before the submission.

**Comment by Lord-Tiger** [comment]
Thanks Abdoul! Added to the proposal document. :)
