### ISSUE TITLE
Misuse insider clinician

### ISSUE THREAD

**Issue by asongne** [Lord-Tiger/CYBR8420_Fall24#5]
![Misuse case updated (1)](https://github.com/user-attachments/assets/a6aed20a-7a76-4a3d-a89a-5339737dac41)

**Comment by Lord-Tiger** [comment]
Hi Abdoul, I think you need to change the lines into dashed ones.

**Comment by asongne** [comment]
all of them?

**Comment by asongne** [comment]
Let me know what you think please
